### ISSUE TITLE
Missing version in cgif.pc

### ISSUE THREAD

**Issue by remicollet** [dloebl/cgif#24]
In generated and installed file:

`Version: undefined`

This will make impossible to check minimal version (if needed) in other tools

**Comment by kleisauke** [comment]
I can confirm this, PR #25 should fix this.

BTW, you might be interested in this SPEC file:
https://github.com/weserv/rpms/blob/master/cgif/cgif.spec

**Comment by remicollet** [comment]
@kleisauke thanks 

btw, I have already wrote my own spec ;)

**Comment by dloebl** [comment]
I will merge #25 and tag a new version today: 0.0.2
