### ISSUE TITLE
Enhancement: support adding (first) frame with transparency

### ISSUE THREAD

**Issue by lovell** [dloebl/cgif#4]
It's common for GIF images to include transparent pixels as part of a frame (often as a single frame "animated" image) and typically this would be the first entry/index in the palette.

I've had a quick go at hacking this into cgif via a `FRAME_ATTR_HAS_TRANSPARENCY` flag and it seems to work.

```diff
diff --git a/cgif.c b/cgif.c
index 81567c0..4154dd1 100644
--- a/cgif.c
+++ b/cgif.c
@@ -556,7 +556,7 @@ int cgif_addframe(GIF* pGIF, FrameConfig* pConfig) {
     pFrame->aGraphicExt[1] = 0xF9;
     pFrame->aGraphicExt[2] = 0x04;
     pFrame->aGraphicExt[3] = 0x04;
-    if(pFrame->config.genFlags & FRAME_GEN_USE_TRANSPARENCY) {
+    if((pFrame->config.genFlags & FRAME_GEN_USE_TRANSPARENCY) || (pConfig->attrFlags & FRAME_ATTR_HAS_TRANSPARENCY)) {
       pFrame->aGraphicExt[3] |= 0x01;
     }
     pFrame->aGraphicExt[6] = pFrame->transIndex;
diff --git a/cgif.h b/cgif.h
index 80e617c..8fb0603 100644
--- a/cgif.h
+++ b/cgif.h
@@ -10,6 +10,7 @@
 #define GIF_ATTR_IS_ANIMATED          (1uL << 1)       // make an animated GIF (default is non-animated GIF)
 #define GIF_ATTR_NO_GLOBAL_TABLE      (1uL << 2)       // disable global color table (global color table is default)
 #define FRAME_ATTR_USE_LOCAL_TABLE    (1uL << 0)       // use a local color table for a frame (local color table is not used by default)
+#define FRAME_ATTR_HAS_TRANSPARENCY   (1uL << 1)       // palette contains transparency at index 0
 // flags to decrease GIF-size
 #define FRAME_GEN_USE_TRANSPARENCY    (1uL << 0)       // use transparency optimization (setting pixels identical to previous frame transparent)
 #define FRAME_GEN_USE_DIFF_WINDOW     (1uL << 1)       // do encoding just for the sub-window that has changed from previous frame
```

It's quite likely there's a better/cleaner way to do this.

I'm happy to submit a PR but would welcome any thoughts/improvements on the approach/API.

**Comment by dloebl** [comment]
I had another look at this issue / your PR #5:
As far as I understand, transparency (that is visible to the user) is nothing the original GIF spec defines.
[https://www.w3.org/Graphics/GIF/spec-gif89a.txt](https://www.w3.org/Graphics/GIF/spec-gif89a.txt)

 **However**, it became the de-facto standard that decoders/image viewers treat the background as transparent. Areas of the first frame that are not defined by the image data are transparent. Disposal method 2 (restore to background) makes it possible to show visible transparency on the following frame(s) as well.

It seems that implementing transparency like this became the new standard. So we will implement it as you suggested 😄

**Comment by dloebl** [comment]
Support for user-defined transparency has been added (your PR #5) and can be set with the global / GIF level attribute `GIF_ATTR_HAS_TRANSPARENCY`.

**Comment by lovell** [comment]
Thank you / danke!
