### ISSUE TITLE
Unable to make animated GIF that doesn't loop

### ISSUE THREAD

**Issue by TheEssem** [dloebl/cgif#46]
I'm trying to encode an animated GIF file that only plays once and then stops. However, when I set `CGIF_Config->numLoops` to 1, it plays twice, and when I set it to 0, it results in an infinite loop, making it impossible to do so. Example GIF:
![freeze (1)](https://user-images.githubusercontent.com/21112968/155435918-dfa5a8ae-ecc7-418a-bcc5-9d964e7ad510.gif)

I re-encoded the GIF with ImageMagick to have a proper loop count, here's what it's supposed to look like:
![ben](https://user-images.githubusercontent.com/21112968/155436230-f757cc6f-2099-471c-a4a3-9ae6ee66e014.gif)

After comparing the two GIFs above in a hex editor, I can see that the one that properly loops doesn't have a `NETSCAPE2.0` application extension. Perhaps there could be a way to specify that it's not needed?

**Comment by dloebl** [comment]
Hi @TheEssem. Thanks for pointing out this issue!

**I had a look into this:**
The _NETSCAPE2.0 loop extension_ is non-standard, so it's not covered by the official GIF specification.
Most decoders I'm aware of handle `numLoops` really as the number of additional repetitions of an animation:
A `numLoops` value of 1 means to repeat the animation one time (two effective loops).
A `numLoops` value of 0 (which is the default in cgif) means to repeat the GIF indefinitely.

To allow your use case I've added a new flag in #48: `CGIF_ATTR_NO_LOOP`
When setting `CGIF_ATTR_NO_LOOP` the value of `numLoops` will be ignored and no _NETSCAPE2.0 extension_ will be written.
I've also added an example for this use case: [tests/noloop.c](https://github.com/dloebl/cgif/blob/no-loop/tests/noloop.c)

Does this work as expected with your use case?
